[package]
name = "elevators"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
eerie = { path = "../eerie" }
rustc-hash = "1.1.0"
